### ISSUE TITLE
Needs adjustments to work on Mac

### ISSUE THREAD

**Issue by mre** [XenGi/speeed#2]
Nice tool and cool idea. 😃 
If I try to run it, on Mac, I get the following error:

```
speeed matthias-endler.de
distance to matthias-endler.de (104.28.24.39): 7714 km
ping: invalid option -- 4
```

The reason is, that the `ipver` flag is not supported on Mac/Darwin/BSD.

Changing line 103 from this
```python
proc = Popen(["ping", self.ipver, self.dest_ip], stdout=PIPE)
```
to this
```python
proc = Popen(["ping", self.dest_ip], stdout=PIPE)
```
will do the trick.

So maybe you want to add a check for Mac and change the `proc` accordingly?
Keep it up!

**Comment by XenGi** [comment]
fixed in v1.0.1
